### PR TITLE
T474, T480

### PR DESCRIPTION
**Pull request by pbca26**

### CODE REVIEW

**Comment by pbca26** [comment]
@jl777 can you check if you can merge it?

this request is probably overlapping with @amarvashi12 previous pull req

**Comment by jl777** [comment]
it says it has conflicts

**Comment by pbca26** [comment]
is it possible to determine which files have conflicts?

**Comment by jl777** [comment]
maybe it needs to be rebased? I am reluctant to merge something with conflicts and I wont be able to resolve the GUI conflicts

**Pull request closed without merging**
