### PR TITLE
Split up m_notary

### PR DESCRIPTION
**Pull request by ghost**
This commit is designed to split up `m_notary` and `m_notary_run` into something more manageable. It is a work in progress and is submitted mostly for discussion, adding to this or changing it is welcome.
In summery:
`m_notary` will work as it always has, people not changing the script can just use this as normal.
The changes I have made are as follows:
1) `m_notary` now kills iguana, does git pull, then calls the `build_iguana` script, this script could maybe take a third option from m_notary to enable SHA256 hardware functions or people using this can just build on their own with a custom script and start from the next script.
2) `m_notary_run` or `m_notary_black` 
`m_notary_black` is an example of how each operator can use custom parameters here for their node. It is what a-team node uses, it is not intended to be merged into the official repo.
3) ` add_coins` is a new script which adds all the coins to iguana, it adds `btc, kmd, chips, game` unlocks the wallet with a `wp_7776` call then builds a list of assetchains from the `assetchains.json` in the komodo repo we are now using. This will automatically add all coins, as 99% of changes to `m_notary_run` are just coins being added. This is no longer required to be a manual operation, just add the coin params to `assetchains.json` and copy the coins file to the `coins` directory.

There are several advantages to this method:
1) You can build iguana while it is still running with `git pull` + `build_iguana` then just call `m_notary_black` which kills iguana and relaunches, this saves time between updates to get back notarizing as fast as possible.
2) New AC are automatically added, so custom `m_notary_run` and build scripts can be used without manually updating things and possibly making mistakes and wasting time.

I tried my best to comment my changes through out the scripts, please take a look and suggest any changes. The latest merge to add an optional `no_split` have broken quite a lot of operators scripts, and we were forced to create alternative ones, and then manually add new coins, which is prone to errors.

### CODE REVIEW

**Comment by lukechilds** [comment]
Great job @blackjok3rtt, I've been meaning to put a PR together for this for a while.

Can I make a suggestion that git pull isn't hardcoded into the build process? Seems like it should be three separate steps to me:

1. Update source (git pull)
2. Build from source
3. Run binary

There are time when I may want to do any one of these three steps individually without the other. I may want to git pull without building, and I may want to build at the current commit without pulling the latest changes.

We can still keep backwards compat and have the default script do all three. But those three steps could be split into three separate files that are called. So I can manually call any single one of those files without triggering the other behaviour.

**Comment by dwygit** [comment]
Or for example, splitting in 3 steps could allow us to just include the run binary mode on our scripts, and use the update/build only manually.

**Comment by patchkez** [comment]
Instead of creating new script for building (iguana/build_iguana), I propose to use Linux Autotools so we could do:
```
./configure
make 
make install
```
This would help us also with containerization. Right now we have to manually copy commands for building into Dockerfile.

**Comment by lukechilds** [comment]
@patchkez that would be even better.

**Comment by kolobus** [comment]
Outdated :)

**Comment by lukechilds** [comment]
@kolobus why is this outdated? Is this functionality already in upstream?

**Pull request closed without merging**
